### ISSUE TITLE
Issues with TFrame compared to original DOS TVision TFrame 

### ISSUE THREAD

**Issue by jcarp-7ab** [magiblot/tvision#166]
I noticed the TFrame is not drawing the lower left (Southwest) corner of a view with the correct characters.  It is placing the "resize" character which is not the way the TFrame is drawn on the DOS version.  I will include pictures to demonstrate.
I saw this behavior when I opened a file in the editor and modified the file.  When a file has changed an asterisk is placed on the frame to note the change in contents.  That drew my attention to the corner. 

I am willing to work on updating the code if someone can point me in the right direction. I am thinking it is an issue in the TFrame object. 

![Screenshot 2024-11-08 10 05 31 PM](https://github.com/user-attachments/assets/52cdcf28-87fa-4429-83db-40b97273e5de)

 I also noticed a difference in the Change Directory dialog, then I figured it is because the old DOS version of the change Directory dialog is not resize-able.  Still the lower corners do not display the same.

![Screenshot 2024-11-08 10 09 50 PM](https://github.com/user-attachments/assets/6d3fd963-02ea-4bff-8f7b-6e486e5f3337)

**Comment by jcarp-7ab** [comment]
@ziotom78 Thank you for the info.  I didn't realize that this was intentional.  That explains this line in "views.h"
    static const char * _NEAR dragLeftIcon;

Please be patient with me, I am new here.  Is there a file that lists all the differences like this one???  If so I'll educate myself.

Also, is there a way I can override the object with my own that does not have a left resize?

**Comment by magiblot** [comment]
Hi @jcarp-7ab!

As you already figured out, this feature is intentional. It is meant to improve user experience.

In the case of the Change Directory dialog, resizing can be disabled by unsetting the `wfGrow` flag of the `flags` member property (inherited from `TWindow`). There is not a simple way for you to disable the left resize handle only, although it would be possible to add such a feature to the Turbo Vision API. From your side, you can create a custom inheritor of `TIndicator` which either avoids drawing the "modified" marker right next to the left resize (if that's the problem), or which draws a normal left corner on top of the left resize handle. But then you would also have to create a custom inheritor of `TEditorWindow` which uses your custom inheritor of `TIndicator`...

New features are listed in the project README, [here](https://github.com/magiblot/tvision#all-platforms) and [here](https://github.com/magiblot/tvision#api-changes), although they could probably be better organized (my bad).

Cheers!

**Comment by jcarp-7ab** [comment]
@magiblot Thank you for the detailed explanation!  I am also reading the links you provided and I see that you called out the left re-size as an intended feature.  My bad for not reading before posting.  Again, I'm learning. We'll just close this issue!
