### ISSUE TITLE
Possible to Cross-Compile?

### ISSUE THREAD

**Issue by sduensin** [magiblot/tvision#17]
I was hoping to cross-compile this for DOS (from Linux) using DJGPP (from https://github.com/andrewwutw/build-djgpp) but my CMake skills are practically non-existent.  Is this possible without a ton of effort?

Thanks!

**Comment by magiblot** [comment]
Hi Scott!

I'm sorry to disappoint you, but no, this is not possible without a ton of effort. It's not because of CMake, but because of the source code: DOS support here has been inherited from the original Turbo Vision, which uses Borland-specific features and assembly. So currently the only way to compile for DOS is to use Borland C++.

https://github.com/set-soft/tvision does have DJGPP support, although you probably already know that port.

Cheers.

**Comment by sduensin** [comment]
I figured that was the case.  I'd much rather have a modern TV than djgpp.  I'll just have to automate compiling via DOSBox or something.  Thanks again!

**Comment by magiblot** [comment]
You are welcome.

> I'll just have to automate compiling via DOSBox or something.

I haven't been able to build this with dosemu2 or DOSBox. In order to build with Borland C++ I use a 32-bit Windows XP VM and store the repository in a shared folder.

DOS is the least tested platform in this port, so it may have regressions. If you find something that's not quite right, feel free to submit an issue.

Have fun!
