### ISSUE TITLE
Support for Unicode in PuTTY and Windows conhost

### ISSUE THREAD

**Issue by electroly** [magiblot/tvision#44]
I'm trying to use UTF-8 in my help file, but it seems like some common terminals don't support Unicode. I've prepared a test program: <https://gist.github.com/electroly/8965f566fa4546eac186a28a9d364c35>.

![image](https://user-images.githubusercontent.com/171909/105958046-79ad9000-6050-11eb-943d-2594f22c4fc5.png)

It seems that macOS iTerm2, macOS Terminal, and Windows Terminal have full Unicode support, but PuTTY and the Windows conhost do not. I have "legacy mode" disabled in the Windows console, and I'm using a TrueType font. Does this match your experience, or is there some way to improve the platform support? I haven't tried to build tvision using Visual Studio; might this be different if I did?

This is an unfortunate situation on Windows. Windows Terminal doesn't seem to support the mouse, and conhost doesn't seem to support Unicode, so none of the terminal options on Windows support all tvision features. The macOS Terminal similarly doesn't seem to support the mouse, but least iTerm2 is available for Macs and it supports both the mouse and Unicode. Do you know of a terminal on Windows that supports both the mouse and Unicode?

**Comment by magiblot** [comment]
Hi Brian,

Conhost does support Unicode, but it does not support fallback fonts. This is why some characters are drawn as boxes. This means that if the user uses a font which supports their native language alphabet, he'll be able to write in it without issues. But things like emojis are less likely to work. Personally, I always use Conhost on Windows.

Whenever you see Unicode being printed as CP437 (i.e. the Putty picture), the issue is in the server side, where the application is running. Turbo Vision uses two locale-dependent funcions to process Unicode text: `mbrtowc` and `wcwidth`. These will only work as expected using a UTF-8 locale (e.g. `export LC_ALL=en_US.UTF-8). Make sure at least LC_CTYPE is set to a Unicode locale.

I know that not all Unix systems use a UTF-8 locale by default, and that this may result in unexpected behaviour in Turbo Vision. But working around this within the application is not straight-forward and I'm not sure whether I should try to do it anyway or just ask users to change their locale settings.

Cheers.

**Comment by electroly** [comment]
Thanks for the detailed info! I followed my nose a bit based on your explanation and found that when I use PuTTY to run the test program inside my development Docker container, I get the garbled output seen in my screenshot above. But if I use the same PuTTY session to run the test program on the host OS, I get correct display of all Unicode symbols, with whatever the built-in default LC_ALL and LC_CTYPE values are.

![image](https://user-images.githubusercontent.com/171909/106022184-f3b73680-609b-11eb-90b8-9a9262763a51.png)

I tried to set LC_ALL inside the Docker container as you described, but I got `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory`. This suggested to me that the Docker container is missing some dependency or configuration that enables the UTF-8 locale. I did some searching around which suggested that, on Ubuntu, the `language-pack-en` package should be installed. This causes the `en_US.UTF-8` locale to be generated, and then after setting LC_ALL as you specified, emoji works inside the Docker container too. This seems to be installed and configured by default on Ubuntu but is simply not included in the base Docker image, so I'm guessing this will not be an issue for real life Linux users.

Too bad about the emoji on Windows conhost. I was hoping that the use of emoji could let users create simple games and such with a bit more flash than typical console apps, but c'est la vie. I expect Windows conhost to be the most common platform for TMBASIC users, so I will probably have to avoid suggesting in the documentation that emoji will work.

Thank you for all the help!
