### ISSUE TITLE
A few thoughts about the library...

### ISSUE THREAD

**Issue by IngvarRiga** [magiblot/tvision#64]
Greetings again!
Thank you for the work done to adapt the library. I will allow myself a few remarks, which I ask you not to take as a reproach.

1. I think that maintaining compatibility with compilers that have died is unnecessary. With all due respect to Borland, their compiler is a corpse. Therefore, I think the compatibility code with it can be removed, leaving only a link to the copyright.
2. TurboVision itself, with all its advantages, has a lot of disadvantages, such as a very poor palette of control elements, the absence of some obvious functions (for example, window centering), etc. I think it's worth creatively expanding the functionality of the library with existing code.
3. When compiling to MSVC, a warning occurs, which may lead to errors in the future. I am sending a message:

...>cmake . -B ./build -A x64 
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.26.28805.0
-- The CXX compiler identification is MSVC 19.26.28805.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORTS_COUNTER_MACRO
-- Performing Test SUPPORTS_COUNTER_MACRO - Success
-- Install path: C:/Program Files/tvision
-- Build Examples: ON
-- Link w/static RTL: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Design/tv_prj/tv/build

...>cmake --build ./build --config Release 
Microsoft (R) Build Engine версии 16.6.0+5ff7b0c9e для .NET Framework
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Checking Build System
  Building Custom Rule D:/Design/tv_prj/tv/source/CMakeLists.txt
  cmake_pch.cxx
....
  help.cpp
  helpbase.cpp
  histlist.cpp
D:\Design\tv_prj\tv\source\tvision\histlist.cpp(189,39): warning C4291: void *HistRec::operator new(size_t,HistRec *) noexcept: the corresponding delete operator was not found; if an exception occurs during initialization, the memory will not be freed [D:\Design\tv_prj\tv\build\source\tvision.vcxproj]
D:\Design\tv_prj\tv\source\tvision\histlist.cpp(55): message : см. объявление "HistRec::operator new" [D:\Design\tv_prj\tv\build\source\tvision.vcxproj]
  mapcolor.cpp
  menu.cpp
....
I'm sorry if my English is not very clear. My native language is Russian, I read normally, but I don't really speak and write))) - I use an automatic translator.

**Comment by IngvarRiga** [comment]
...and the saddest thing... there is no normal port on C#!

**Comment by magiblot** [comment]
Hi Alexey! Your comments are welcome!

> I think that maintaining compatibility with compilers that have died is unnecessary. With all due respect to Borland, their compiler is a corpse. Therefore, I think the compatibility code with it can be removed, leaving only a link to the copyright.

You don't need to worry about this, because backwards-compatibility is only necessary for the original API and it doesn't prevent me from making new features available on modern systems. For example, I added support for Unicode and 24-bit color without having to remove the Borland C++ code. I insist on keeping compatibility with the Borland compiler because from time to time I like to play with it and because I find it an interesting challenge. The restraint of having to stay source-code-compatible has forced me to find creative solutions and has led me to learn more things about C++. I'm happy with it.

> TurboVision itself, with all its advantages, has a lot of disadvantages, such as a very poor palette of control elements, the absence of some obvious functions (for example, window centering), etc. I think it's worth creatively expanding the functionality of the library with existing code.

Turbo Vision has *many* disadvantages. Let me add more to the list:

* It requires inheriting existing classes and manually calling the parent version of overriden methods. In the end, this means that the developer has to understand the class hierarchy and has to know implementation details of the superclasses.
* Creating bindings for other languages is challenging because of inheritance, public class members, memory management...
* The behaviour and layout of views cannot be specified in a declarative way. You must program imperatively and you have to be aware of mutable state.

Regarding the two points you mentioned, my initial idea was to provide an easy way for people to reuse extra widgets and utility functions from secondary projects instead of having to provide everything here, in the main library. For example, the [Turbo](https://github.com/magiblot/turbo) project has its own text editing component and the [TMBASIC](https://github.com/electroly/tmbasic) application makes use of it instead of the default `TEditor`. However, connecting several Turbo Vision projects with CMake is not trivial. I still have to look more into it.

> When compiling to MSVC, a warning occurs, which may lead to errors in the future. I am sending a message:

MSVC is being stupid here. First: that implementation of `operator new` does not allocate memory, so it will never cause a leak. Second: the `HistRec` constructor is `noexcept`, so it cannot even throw an exception in the first place.

> ...and the saddest thing... there is no normal port on C#!

If it may help, someone wrote a C# port of Turbo Vision *just for fun*: https://github.com/10der/tvision. However, it's based on [SET's Turbo Vision](https://github.com/set-soft/tvision) rather than mine.

Cheers!

**Comment by IngvarRiga** [comment]
Greetings!
As I meant, my arguments do not claim to be the ultimate truth :). I just shared my opinion, so your answer quite satisfied me. In any case, your project is very helpful to me in my current work. If there are any suggestions, I will let you know. Good luck and don't get sick!

**Comment by IngvarRiga** [comment]
https://github.com/MarkMLl/Dialedit3b TV Dialog Designer. Do you see that?

**Comment by magiblot** [comment]
No, I hadn't, thanks for pointing it out. But it's in Pascal, so in order to make it work with my version of the library it would have to be rewritten in C++.

**Comment by IngvarRiga** [comment]
Good day and Happy New Year! Best wishes!
I ask for a little help: I am very tired of forming dialogs manually, and those dialog box editors that exist are either not finished, or run from under DOS BOX - which is very inconvenient. In this regard, I write my own editor in my free time (as I do, I will share the source code). I came across a problem that bothers me: I can't write the redefined dialog and, accordingly, all the components inserted into it (also redefined) to the stream (resource file). It seems like I'm doing everything as it says, but something doesn't work. The program just crashes. If possible, send me a link to the step-by-step instructions for TV c++ how to do it, or even better - a ready-made example (in the source code). Simple to the limit.

**Comment by magiblot** [comment]
Hi Alexey! Happy New Year!

I don't think I have any guide on how to do this. For me it would be easier to run your dialog box editor and try to find out why it is not working. You can mail me at magiblot@hotmail.com if you don't mind sharing your source code in private.

Cheers!

**Comment by IngvarRiga** [comment]
Hi! Thanks again for the help. I couldn't resist and tried your advice, everything works, thank you for your help! 

Regarding the use of JSON ->, I think that the use of saving dialogs in streams is only for the possibility of re-editing once created dialogs. So the problem of compatibility between 32/64 does not play a decisive role. 

In any case, I am now writing an editor, whether I have the determination to finish the job or not, I do not know. But in any case, if you need it or someone else wants it, I'm ready to merge the source code at the first request. The archive of the project in the source code.  You never know who else will want to write, so at least let him not start from scratch.

**Comment by magiblot** [comment]
> I think that the use of saving dialogs in streams is only for the possibility of re-editing once created dialogs.

Ah, in that case it's fine! I thought that the resource files would have to be loaded by the client application.

**Comment by IngvarRiga** [comment]
Greetings!
I found an error (quite possibly I don't understand something): Russian Russian letters are normally displayed if they are written directly in the source code saved in unicode, however, the input string does not allow you to enter a string of Russian characters in the running application, despite the fact that the console normally switches enters and displays.
Win 10 x64 / build on TDM MinGW x64.

Second: When redefining components for the dialog editor, I came across the fact that the same properties of objects (well, used for the same purposes) are called differently, have different isolation levels, etc. For example: the string TStaticText is a protected constant type char *text, and TButton has a public constant type char *title.  Accordingly, such confusion does not allow making normal code. As I understand it, this is the legacy of Turbo Vision itself. It's sad, because if it weren't for the attempt to maintain compatibility with borland c++, the library could have been developed normally. However, this jamb can be overcome, although it is unpleasant. But a mistake in the processing of national symbols is serious.

**Comment by IngvarRiga** [comment]
... and also: sorting files in the TFileDialog window is very strange. The root directory is at the very end, the directories are at the bottom... All dialog boxes put the root at the top, then directories and then files. Is this a bug or a feature?

**Comment by magiblot** [comment]
Hi Alexey!

> the input string does not allow you to enter a string of Russian characters in the running application, despite the fact that the console normally switches enters and displays.

Can you please share a screen recording where you show that? If possible, also record what happens when you run the `tvdemo` application, open the event viewer (`Alt + 0`) and type Russian text in it.

> I came across the fact that the same properties of objects (well, used for the same purposes) are called differently, have different isolation levels, etc. For example: the string TStaticText is a protected constant type char *text, and TButton has a public constant type char *title.

The Turbo Vision API is awful for today's standards, but I do not want to design a new API. I chose to keep most things unchanged so that at least the original documentation remains valid.

> ... and also: sorting files in the TFileDialog window is very strange. The root directory is at the very end, the directories are at the bottom... All dialog boxes put the root at the top, then directories and then files. Is this a bug or a feature?

It is a feature. Turbo Vision file dialogs have always been like this. Of course, this does not justify its poor usability. I thought of writing a more decent file dialog but in the end I didn't get around to do it.

**Comment by IngvarRiga** [comment]
https://github.com/IngvarRiga/TurboVision-dialog-designer

Posted the project in open access without any guarantees. I will occasionally merge the latest version here.
