### ISSUE TITLE
Critical error when entering national symbols in TInputLine.

### ISSUE THREAD

**Issue by IngvarRiga** [magiblot/tvision#68]
Greetings!
It is sad, but a fact, the library contains a critical error that leads to the crash of the program when entering national symbols into the input line of the TInputLine object.

To be honest, I don't know how it will happen on layouts other than Russian. The steps to reproduce the error are as follows:
1. create a dialog box with an input line and a button.
2. activate it
3. move the input focus to the line
4. switch to the national layout
5. select all the text if it is in the input line
6. we start typing the word with a capital letter using "Shift"
... 
in some cases, the library selects non-existent text, that is, the first character is obtained and the selection is green to the end of an empty line, sometimes it simply selects the first symbol and while Shift is clamped, all the symbols are entered into the position where the cursor is. sometimes when you enter several characters, the program crashes.

it is sad that this error does not allow you to work normally

I'm ready to make a video to demonstrate this effect. put it on a file sharing site so that you can see it with your own eyes. I will demonstrate it on my dialog constructor.

yes, this error pops up only in the input line, using TMemo does not lead to such effects.

**Comment by magiblot** [comment]
Hi!

I know you reported this issue to me one month ago. I'm sorry it took so long given that the fix was simple.

This turned out to be a very silly misuse of `strchr` (yet another episode of *things that can go wrong because of null-terminated strings*, with the previous one being #37).

Just today I was also thinking about the other issues you pointed out. Let's see if I can solve them too.

Thanks for the report!

**Comment by magiblot** [comment]
fc24229500c46b8d0a3dda2de753b1d0a017198d provides a workaround for this other issue you pointed out:

> If you set the length of the string (any), then the standard ASCII characters will fit into it as many as specified. But the national symbols fit exactly 2 times less. Probably due to the fact that Unicode is a 2-character.

Indeed, that happens because Russian symbols are multi-byte characters in UTF-8. Since `TInputLine` only allowed specifying a maximum text length in bytes, the number of characters you could enter would vary depending on how many bytes each character takes.

It is now possible to specify a maximum text width or maximum grapheme count in `TInputLine`. This is done through a new parameter in `TInputLine`'s constructor, `ushort limitMode`, which controls how the second constructor parameter, `uint limit`, is to be treated. The `ilXXXX` constants define the possible values of `limitMode`:

* `ilMaxBytes` (the default): the text can be up to `limit` bytes long, including the null terminator.
* `ilMaxWidth`: the text can be up to `limit` columns wide.
* `ilMaxGraphemes`: the text can contain up to `limit` non-combining characters.

So, for example, the following `TInputLine` should accept exactly 30 characters, whether they are ASCII or Russian:

```c++
new TInputLine(TRect(3, 3, 31, 4), 30, nullptr, ilMaxGraphemes);
```

But in any case, the text in a `TInputLine` can never be more than 256 bytes long, including the null terminator.

**Comment by IngvarRiga** [comment]
Greetings! 
Thanks again for the work and for the explanations.
For me, the critical error was when entering into the line, causing the program to crash. The maximum length of the string... not so scary. So as it is, so it is. I'll survive.))
