### ISSUE TITLE
request: C# wrapper

### ISSUE THREAD

**Issue by 486DX2** [magiblot/tvision#85]
Hi

Is there any interest in making a C# wrapper for tvision?
I would be interested since I almost never use C or C++.
I know there are ways C# can call C code but I don't have experience.
But maybe somebody can use this to make a C# wrapper very easily?

Thanks
Lisa

**Comment by 486DX2** [comment]
.NET is also cross platform today so in theory the wrapper could become crossplatform too if underlying tvision is just installed for each platform?
Just some ideas...

**Comment by magiblot** [comment]
Hi!

The problem of writing a C# wrapper is the same as writing a wrapper for any other language: Turbo Vision expects the user to inherit its classes; since inheritance depends on the C++ ABI, writing a wrapper is more complex than just calling C code.

In the case of C#, however, someone already wrote a native port of Turbo Vision: https://github.com/10der/tvision. Although it works a bit different than my port since it replicates the behaviour of https://github.com/set-soft/tvision instead.

**Comment by 486DX2** [comment]
OK, I understand.
